### ISSUE TITLE
Click crashes when given an invalid DAG

### ISSUE THREAD

**Issue by drbarrett** [XIA-Project/xia-core#2]
Reported by drbarrett

To reproduce: 
Create a partial DAG or a DAG with improper formatting such as 
CID:nnnnnnnnnnnnnn

Click will crash in Vector class.

Comment 1 by Dongsu Han, May 21, 2012

Is the problem caused in XIAPath::parse?
I think the easiest fix would be to catch an exception when we parse 
string to DAG. There's no syntax checker for our DAG string 
representation.

Comment 2 by Me, May 21, 2012

That's basically what I was thinking. Stopping the crash should be 
easy. Doing the right thing to let the app the caused the problem 
know might be more involved. I haven't looked at the code yet to see.

Comment 3 by Me, May 24, 2012

XIAPath::parse returns false if it can't parse the DAG. None of the 
dozen or so places in transport.cc check the return value, and will 
cause click to crash if the DAG is invalid. 

API calls where the caller sends us a DAG such as Xbind, XSendto, 
Xrecvfrom are most at rise for problems. Several other places where 
XAIPath::parse is called use DAGs created internally. So while they 
should be fixed, they aren't likely to cause a crash.

**Comment by drbarrett** [comment]
xiapath now has exception handling

**Comment by cmuyanlinli** [comment]
Hi Dan,

Can you please unsubscribe me from this list? Thanks.

Best wishes,
Yanlin
